# Generated by Django 4.2.7 on 2023-11-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store_app', '0004_product_image_large_product_image_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='products',
        ),
        migrations.AddField(
            model_name='basket',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Всего по продукту')),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basketproduct', to='online_store_app.basket', verbose_name='Корзина-Продукт')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basketproduct', to='online_store_app.product', verbose_name='Продукт')),
            ],
        ),
    ]
