# Generated by Django 4.2.7 on 2023-11-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store_app', '0008_alter_category_image_alter_product_image_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproduct',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basketproduct', to='online_store_app.basket', verbose_name='Корзина-Продукт'),
        ),
    ]
