# Generated by Django 4.2.7 on 2023-11-08 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store_app', '0009_alter_basketproduct_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_store_app.image', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_large',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_large', to='online_store_app.image', verbose_name='Фото бол.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_medium', to='online_store_app.image', verbose_name='Фото ср.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_small',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_small', to='online_store_app.image', verbose_name='Фото мал.'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_store_app.image', verbose_name='Фото'),
        ),
    ]
